name: Pull Request Test

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ matrix.node-version }}.x
      uses: actions/setup-node@main
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true
    - name: Npm Build
      run: npm run initial --if-present ; npm run export-legacy --if-present
